# Generated by Django 5.2.3 on 2025-08-05 18:28

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorizacaoAcessoGovModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a autorização de acesso ao Gov.', upload_to=app_automacoes.models.upload_to_autorizacao_acesso_gov, verbose_name='PDF Base para Autorização de Acesso ao Gov')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='AutorizacaoDireitoImagemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a autorização de direito de imagem.', upload_to=app_automacoes.models.uoload_to_autorizacao_direito_imagem, verbose_name='PDF Base para Autorização de Direito de Imagem')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='CarteirinhaAssociadoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a Carteirinha do Associado.', upload_to=app_automacoes.models.upload_to_carteirinha_apapesc, verbose_name='PDF Base para Carteirinha do Associado')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='CertificadoAssociadoLegalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para o certificado de associado legal.', upload_to=app_automacoes.models.upload_to_certificado_associado_legal, verbose_name='PDF Base para Certificado de Associado Legal')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='CobrancaAnuidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a Cobrança/Anuidades.', upload_to=app_automacoes.models.upload_to_cobranca_anuidade, verbose_name='PDF Base para Cobrança Anuidade')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoAtividadePesqueiraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a declaração de Atividade Pesqueira.', upload_to=app_automacoes.models.upload_to_declaracao_atividade_pesqueira, verbose_name='PDF Base para Declaração de Atividade Pesqueira')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoDesfiliacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a declaração de desfiliação.', upload_to=app_automacoes.models.upload_to_declaracao_desfiliacao, verbose_name='PDF Base para Declaração de Desfiliação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoFiliacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a declaração de filiação.', upload_to=app_automacoes.models.upload_to_declaracao_filiacao, verbose_name='PDF Base para Declaração de Filiação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='DeclaracaoHipossuficienciaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a declaração de Atividade Pesqueira.', upload_to=app_automacoes.models.upload_to_declaracao_hipossuficiencia, verbose_name='PDF Base para Declaração de Hipossuficiência')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='DireitosDeveres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para Regramentos Direitos e Deveres.', upload_to=app_automacoes.models.upload_to_direitos_deveres, verbose_name='PDF Base para Regramentos Direitos e Deveres')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='ProcuracaoAdministrativaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a procuração administrativa.', upload_to=app_automacoes.models.upload_to_procuracao_administrativa, verbose_name='PDF Base para Procuração Administrativa')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='ProcuracaoJuridicaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a procuração jurídica.', upload_to=app_automacoes.models.upload_to_procuracao_juridica, verbose_name='PDF Base para Procuração Jurídica')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboAnuidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a Recibos/Anuidades.', upload_to=app_automacoes.models.upload_to_recibo_anuidade, verbose_name='PDF Base para Recibo Anuidade')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='ReciboServicoExtraModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a Recibos/Serviço Extra.', upload_to=app_automacoes.models.upload_to_recibo_servico_extra, verbose_name='PDF Base para Recibo Serviço Extra')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='RetiradaDocumentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para declaração de retiradda de documentos.', upload_to=app_automacoes.models.upload_to_retirada_documentos, verbose_name='PDF Base para declaração de retiradda de documentos')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
        migrations.CreateModel(
            name='TermoCompromissoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para o termo de compromisso.', upload_to=app_automacoes.models.upload_to_termo_compromisso, verbose_name='PDF Base para Termo de Compromisso')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
