# Generated by Django 5.2.3 on 2025-08-23 23:32

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0002_autorizacaoacessogovmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcialReciboAnuidadeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para a Parcial Recibos/Anuidades.', upload_to=app_automacoes.models.upload_to_parcial_recibo_anuidade, verbose_name='PDF Base para Parcial Recibo Anuidade')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
