# Generated by Django 5.2.3 on 2025-08-24 20:31

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0003_parcialreciboanuidademodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeclaracaoDeVeracidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para declaração de veracidade.', upload_to=app_automacoes.models.upload_to_declaracao_veracidade, verbose_name='PDF Base para declaração de vereaciade')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
