# Generated by Django 5.2.3 on 2025-11-30 18:52

import app_automacoes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_automacoes', '0004_declaracaodeveracidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequerimentoFiliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_base', models.FileField(help_text='Substituirá o arquivo base atual para requerimento de filiação.', upload_to=app_automacoes.models.upload_to_requerimento_filiacao, verbose_name='PDF Base para requerimento de filiação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
        ),
    ]
