# Generated by Django 5.2.3 on 2025-10-26 02:00

import app_uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_uploads', '0002_tipodocumentoup_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadsdocs',
            name='arquivo',
            field=models.FileField(upload_to=app_uploads.models.upload_to_path, validators=[app_uploads.models.validate_file_extension]),
        ),
    ]
