# Generated by Django 5.2.3 on 2025-11-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_servicos', '0006_alter_pagamentoentrada_valor_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalservicomodel',
            name='tipo_servico',
            field=models.CharField(max_length=100, verbose_name='Tipo Serviço'),
        ),
        migrations.AlterField(
            model_name='servicomodel',
            name='tipo_servico',
            field=models.CharField(max_length=100, verbose_name='Tipo Serviço'),
        ),
    ]
