# Generated by Django 5.2.3 on 2025-10-12 19:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associados', '0005_alter_associadomodel_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbarcacoesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destaque_embarcacao_img', models.ImageField(blank=True, null=True, upload_to='embarcacoes/destaques/', verbose_name='Imagem em destaque da embarcação')),
                ('nome_embarcacao', models.CharField(max_length=100)),
                ('inscricao_embarcacao', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Inscrição')),
                ('tipo_embarcacao', models.CharField(blank=True, choices=[('canoa', 'Canoa'), ('bote', 'Bote'), ('traineira', 'Traineira'), ('atuaneiro', 'Atuaneiro'), ('Outro', 'Outro')], max_length=50, null=True, verbose_name='Tipo de Embarcação')),
                ('validade_tie', models.DateField(verbose_name='Validade da TIE')),
                ('atividade', models.CharField(max_length=100)),
                ('area_navegacao', models.CharField(max_length=100)),
                ('numero_tripulantes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('numero_passageiros', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('porte', models.CharField(blank=True, choices=[('miuda', 'Miuda'), ('maior porte', 'Maior Porte')], max_length=25, null=True)),
                ('cumprimento', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('ab_gt', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Arqueação Bruta (AB/GT)')),
                ('boca', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('tipo_propulsao', models.CharField(blank=True, choices=[('motor', 'Motor'), ('vela', 'Vela'), ('remo', 'Remo'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Tipo de Propulsão')),
                ('combustivel', models.CharField(choices=[('alcool', 'Álcool'), ('bateria', 'Bateria'), ('diesel', 'Diesel'), ('gasolina', 'Gasolina'), ('gas', 'Gás'), ('nao usa', 'Não Usa')], max_length=15)),
                ('motor_1', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie_1', models.CharField(blank=True, max_length=100, null=True)),
                ('potencia_hp1', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_2', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie_2', models.CharField(blank=True, max_length=100, null=True)),
                ('potencia_hp2', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_3', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie_3', models.CharField(blank=True, max_length=100, null=True)),
                ('potencia_hp3', models.CharField(blank=True, max_length=100, null=True)),
                ('motor_4', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie_4', models.CharField(blank=True, max_length=100, null=True)),
                ('potencia_hp4', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_construcao', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ano de Construção')),
                ('construtor_nome', models.CharField(blank=True, max_length=100, null=True)),
                ('material_construcao', models.CharField(blank=True, max_length=100, null=True)),
                ('alienacao', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5)),
                ('co_proprietario_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Co-Proprietário')),
                ('municipio_emissao', models.CharField(max_length=100)),
                ('data_emissao', models.DateField()),
                ('data_atualizacao', models.DateField(auto_now=True)),
                ('traves_img', models.ImageField(blank=True, null=True, upload_to='embarcacoes/traves/', verbose_name='Imagem da Trave (bordo)')),
                ('popa_img', models.ImageField(blank=True, null=True, upload_to='embarcacoes/popa/', verbose_name='Imagem da Popa')),
                ('seguro_dpem', models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], default='nao', max_length=5, verbose_name='Possui DPEM?')),
                ('seguro_dpem_numero', models.CharField(blank=True, max_length=100, null=True)),
                ('seguro_dpem_data_vencimento', models.DateField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarcacoes', to='app_associados.associadomodel', verbose_name='Proprietário')),
            ],
            options={
                'verbose_name': 'Embarcação',
                'verbose_name_plural': 'Embarcações',
                'ordering': ['nome_embarcacao'],
            },
        ),
    ]
