# Generated by Django 5.2.3 on 2025-10-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_embarcacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='codigo_frota',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='documento_licenca',
            field=models.FileField(blank=True, null=True, upload_to='embarcacoes/documentos/licenca/', verbose_name='Documento da Licença'),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='documento_tie',
            field=models.FileField(blank=True, null=True, upload_to='embarcacoes/documentos/tie/', verbose_name='Documento da TIE'),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='inscricao_aut_naval',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='licenca_nome',
            field=models.CharField(blank=True, choices=[('registro_licenca_embarcacao', 'Certificado de Registro e Autorização de Embarcação Pesqueira')], max_length=50, null=True, verbose_name='Nome da Licença'),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='orgao_emissor_nome',
            field=models.CharField(blank=True, choices=[('MAPA', 'Ministério da Agricultura, Pecuária e Abastecimento'), ('IBAMA', 'IBAMA'), ('MMA', 'Ministério do Meio Ambiente'), ('SPU', 'Secretaria do Patrimônio da União')], max_length=50, null=True, verbose_name='Órgão Emissor'),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='validade_licenca_final',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Final da Licença'),
        ),
        migrations.AddField(
            model_name='embarcacoesmodel',
            name='validade_licenca_inicial',
            field=models.DateField(blank=True, null=True, verbose_name='Validade Inicial da Licença'),
        ),
    ]
