# Generated by Django 5.2.3 on 2025-10-30 02:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_associacao', '0005_alter_reparticoesmodel_nome_reparticao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaAssociacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_despesa', models.CharField(blank=True, choices=[('aluguel', 'Aluguel'), ('internet', 'Internet'), ('tranposrte', 'Transporte'), ('uber', 'Uber'), ('gcp_hospedagem', 'GCP/Hospedagem'), ('matuntencao', 'Manutenção'), ('pagamento_honorarios', 'Pagamento/Honorários'), ('credito_celular', 'Crédito Celular'), ('prestacao_servicos', 'Prestação de Serviços'), ('papelaria', 'Papelaria'), ('outros', 'Outros')], default='Outros', max_length=150, verbose_name='Tipo de Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor da Despesa')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('numero_nota_fiscal', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número da Nota Fiscal')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_lancamento', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Lançamento')),
                ('pago', models.BooleanField(default=False, verbose_name='Despesa Paga')),
                ('comprovante_nota', models.FileField(blank=True, help_text='Upload do comprovante em PDF, JPG ou PNG.', null=True, upload_to='comprovantes_despesas/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Comprovante / Nota Fiscal')),
                ('data_upload_comprovante', models.DateTimeField(blank=True, null=True, verbose_name='Data do Upload do Comprovante')),
                ('associacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='app_associacao.associacaomodel', verbose_name='Associação')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Registros', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('reparticao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas', to='app_associacao.reparticoesmodel', verbose_name='Repartição')),
            ],
            options={
                'verbose_name': 'Despesa da Associação',
                'verbose_name_plural': 'Despesas das Associações',
                'ordering': ['-data_vencimento'],
            },
        ),
    ]
