# Generated by Django 5.2.3 on 2025-11-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0011_alter_processamentosegurodefesomodel_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlebeneficiomodel',
            name='status_pedido',
            field=models.CharField(choices=[('EM_PREPARO', 'Em Preparo'), ('PROTOCOLADO_EM_ANALISE', 'Protocolado, em Análise'), ('EM_EXIGENCIA', 'Em Exigência'), ('CUMPRIDA_EXIGENCIA_EM_ANALISE', 'Exigência cumprida, em Análise'), ('CONCEDIDO', 'Concedido'), ('NEGADO', 'Negado'), ('RECURSO', 'Recurso'), ('CANCELADO', 'Cancelado')], default='EM_PREPARO', help_text='Status atual do benefício', max_length=40),
        ),
        migrations.AlterField(
            model_name='historicalcontrolebeneficiomodel',
            name='status_pedido',
            field=models.CharField(choices=[('EM_PREPARO', 'Em Preparo'), ('PROTOCOLADO_EM_ANALISE', 'Protocolado, em Análise'), ('EM_EXIGENCIA', 'Em Exigência'), ('CUMPRIDA_EXIGENCIA_EM_ANALISE', 'Exigência cumprida, em Análise'), ('CONCEDIDO', 'Concedido'), ('NEGADO', 'Negado'), ('RECURSO', 'Recurso'), ('CANCELADO', 'Cancelado')], default='EM_PREPARO', help_text='Status atual do benefício', max_length=40),
        ),
    ]
