# Generated by Django 5.2.3 on 2025-12-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_defeso', '0012_alter_controlebeneficiomodel_status_pedido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlebeneficiomodel',
            name='dar_entrada',
            field=models.CharField(blank=True, choices=[('DEZ', 'Dezembro'), ('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Março')], help_text='Mês em que foi dada a entrada do Seguro Defeso', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='historicalcontrolebeneficiomodel',
            name='dar_entrada',
            field=models.CharField(blank=True, choices=[('DEZ', 'Dezembro'), ('JAN', 'Janeiro'), ('FEV', 'Fevereiro'), ('MAR', 'Março')], help_text='Mês em que foi dada a entrada do Seguro Defeso', max_length=3, null=True),
        ),
    ]
