# Generated by Django 5.2.3 on 2025-10-22 00:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0005_alter_associadomodel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='celular_correspondencia',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\d{5}-\\d{4}$', 'Número inválido. O telefone deve conter 10 ou 11 dígitos, ex: (48)99999-9999.')]),
        ),
        migrations.AlterField(
            model_name='historicalassociadomodel',
            name='celular_correspondencia',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\(\\d{2}\\)\\d{5}-\\d{4}$', 'Número inválido. O telefone deve conter 10 ou 11 dígitos, ex: (48)99999-9999.')]),
        ),
    ]
