# Generated by Django 5.2.3 on 2025-11-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0006_alter_associadomodel_celular_correspondencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='rg_numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número do RG - CIN'),
        ),
        migrations.AlterField(
            model_name='historicalassociadomodel',
            name='rg_numero',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='Número do RG - CIN'),
        ),
    ]
