# Generated by Django 5.2.3 on 2025-11-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0007_alter_associadomodel_rg_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='caepef',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CAEPF'),
        ),
        migrations.AlterField(
            model_name='historicalassociadomodel',
            name='caepef',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do CAEPF'),
        ),
    ]
