# Generated by Django 5.2.3 on 2025-11-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_associados', '0008_alter_associadomodel_caepef_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associadomodel',
            name='casa_onde_mora',
            field=models.CharField(blank=True, choices=[('Mora em casa prórpia', 'Mora em casa prórpia'), ('Mora em casa augada', 'Mora em casa augada'), ('Mora em casa cedida', 'Mora em casa cedida'), ('Mora em casa de terceiros', 'Mora em casa de terceiros'), ('Undefined ', 'Undefined')], default='Não declarado', max_length=50, null=True, verbose_name='Mora em:'),
        ),
        migrations.AlterField(
            model_name='historicalassociadomodel',
            name='casa_onde_mora',
            field=models.CharField(blank=True, choices=[('Mora em casa prórpia', 'Mora em casa prórpia'), ('Mora em casa augada', 'Mora em casa augada'), ('Mora em casa cedida', 'Mora em casa cedida'), ('Mora em casa de terceiros', 'Mora em casa de terceiros'), ('Undefined ', 'Undefined')], default='Não declarado', max_length=50, null=True, verbose_name='Mora em:'),
        ),
    ]
